import React from 'react';
import { GuideSection, PromptBlock } from './GuideComponents';

interface ReeplGuideProps {
  onBack: () => void;
}

const ReeplGuide: React.FC<ReeplGuideProps> = ({ onBack }) => {
  return (
    <div className="bg-white py-12 animate-fade-in">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
        <button onClick={onBack} className="mb-8 text-blue-600 font-semibold hover:text-blue-800 transition-colors">
          &larr; Back to All Guides
        </button>

        <header className="mb-10 text-center">
            <h1 className="text-4xl sm:text-5xl font-extrabold text-slate-900 tracking-tight">Reepl — AI Content Generation Guide</h1>
            <p className="mt-4 text-lg text-slate-600">Learn how to generate engaging LinkedIn posts and carousels using AI.</p>
        </header>
        
        <GuideSection title="1. What You Need to Start">
            <ol className="list-decimal list-inside space-y-2">
                <li>A topic or idea for a LinkedIn post (e.g., "The future of remote work," "A recent project success").</li>
                <li>Your target audience (e.g., "Software Engineers," "Marketing Managers").</li>
                <li>Key takeaways or bullet points you want to cover in your post.</li>
            </ol>
        </GuideSection>

        <GuideSection title="2. Generating a Post with Reepl">
            <ol className="list-decimal list-inside space-y-2">
                <li>Go to the Reepl AI content generator tool.</li>
                <li>Enter your post topic and key points into the input field.</li>
                <li>Specify the desired tone (e.g., "Professional," "Inspirational," "Technical").</li>
                <li>Select the format (e.g., "Text Post," "Carousel Idea," "Poll Question").</li>
                <li>Click "Generate" and review the AI-created content.</li>
            </ol>
        </GuideSection>

        <GuideSection title="3. Master Prompt for High-Quality Content">
          <p>Use this detailed prompt structure for the best results:</p>
          <PromptBlock>
            “Create a LinkedIn post for [Target Audience]. The topic is [Your Topic]. Cover these key points: [Point 1], [Point 2], [Point 3]. The tone should be [Tone]. End with a question to encourage comments. Include 3-5 relevant hashtags.”
          </PromptBlock>
        </GuideSection>

        <GuideSection title="4. Prompts for Refining Content">
          <h3 className="text-xl font-bold mt-4 mb-2 text-slate-800">A — Making it More Concise</h3>
          <PromptBlock>
            “Take this draft and make it 30% shorter without losing the core message. Focus on clarity and impact.”
          </PromptBlock>

          <h3 className="text-xl font-bold mt-6 mb-2 text-slate-800">B — Generating Carousel Slides</h3>
          <PromptBlock>
            “Turn this post into a 5-slide carousel script. Each slide should have a clear heading and 1-2 sentences of text. The last slide should be a call-to-action.”
          </PromptBlock>
        </GuideSection>

        <GuideSection title="5. Best Practices">
            <ul className="list-disc list-inside space-y-2">
                <li><strong>Always Edit:</strong> Use the AI output as a first draft. Add your personal voice, stories, and specific examples.</li>
                <li><strong>Check for Accuracy:</strong> Fact-check any data or claims generated by the AI.</li>
                <li><strong>Format for Readability:</strong> Use short paragraphs, bullet points, and emojis to break up text and make it easy to scan.</li>
                <li><strong>Engage with Comments:</strong> The goal of a post is to start a conversation. Reply to comments to boost visibility.</li>
            </ul>
        </GuideSection>

        <div className="text-center mt-12">
            <button onClick={onBack} className="bg-blue-600 text-white font-bold py-3 px-6 rounded-lg text-lg hover:bg-blue-700 transition-colors shadow-lg transform hover:scale-105">
              Back to All Guides
            </button>
        </div>
      </div>
    </div>
  );
};

export default ReeplGuide;